### ISSUE TITLE
[Other issue]: Obstacle not visualized in Rviz and lanes not closing

### ISSUE THREAD

**Issue by Jerrybaoyilei** [open-rmf/rmf_obstacle#30]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

# Description of bug

Hi @Yadunund , I have got the `rmf_obstacle_detector_laserscan` and `rmf_obstacle_ros2` running without problem. However, when I look into RViz, the obstacle is not visualized.... I also tried to show the marker array and I got the following error for the obstacle related markers:

```
No transformation to fixed frame [map]. TF Error: [Lookup would require extrapolation into the past. Requested time 752.140000 but the earliest data is at time 1713146076.663062, when looking up transform from fram...

```

What I don't understand is: 1. I already ran a ros_gz_bridge to sync up the time in Gazebo and ROS 2; 2. I also have a Transform Publisher that publishes the tf data from the fixed map frame to the lidar. (I have attached the bridge config yaml file and the transform python file)

Also, I can see the obstacles message in `/rmf_obstacles` topic. The laserscan node output seems like it's detecting the obstacle. The lane blocker node is recognizing the conflict with paths, but just not closing the paths.

Below is a sample of the rmf_obstacles topic echo result:

```
---
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: VelodyneHDL-32/top/gpu_lidar
obstacles:
- header:
    stamp:
      sec: 1712952983
      nanosec: 129420824
    frame_id: VelodyneHDL-32/top/gpu_lidar
  id: 0
  source: rmf_obstacle_detector_laserscan
  level_name: L1
  classification: obstacle
  bbox:
    center:
      position:
        x: 6.093079302207245
        y: 0.033275952827119655
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    size:
      x: 0.8890608627928119
      y: 0.8890608627928119
      z: 0.8890608627928119
  data_resolution: 0.0
  data: []
  lifetime:
    sec: 1
    nanosec: 0
  action: 1
---

```

Below is a sample of the lane blocker node terminal output:

```
Checking collision between:
Lane: {18.767,-8.62319,1.55511} [3.49886,0.5]
obs: {18.7976,-8.03186,-1.5708} [0.976989,-0.976989]
Obs rot matrix:
2.83277e-16           1
         -1 2.83277e-16
Obs vertices before trans: {18.3091,-7.54337} {19.2861,-7.54337} {18.3091,-8.52035} {19.2861,-8.52035}
Lane rot inv matrix:
0.0156901  0.999877
-0.999877 0.0156901
Obs vertices after trans: {1.07251,0.474788} {1.08784,-0.50208} {0.0956431,0.459459} {0.110972,-0.517409}
Lane box_min: -1.74943,-0.25
Lane box_max: 1.74943,0.25
obs transformed box_min: 0.0956431,-0.517409
obs transformed box_max: 1.08784,0.474788
[INFO] [1712780669.766379482] [lane_blocker_node]: Obstacle rmf_obstacle_detector_laserscan_0 is still in the vicinity of lane tinyRobot_42
================================================
Checking collision between:
Lane: {18.767,-8.62319,1.55511} [3.49886,0.5]
obs: {18.7976,-8.03186,-1.5708} [0.976989,-0.976989]
Obs rot matrix:
2.83277e-16           1
         -1 2.83277e-16
Obs vertices before trans: {18.3091,-7.54337} {19.2861,-7.54337} {18.3091,-8.52035} {19.2861,-8.52035}
Lane rot inv matrix:
0.0156901  0.999877
-0.999877 0.0156901
Obs vertices after trans: {1.07251,0.474788} {1.08784,-0.50208} {0.0956431,0.459459} {0.110972,-0.517409}
Lane box_min: -1.74943,-0.25
Lane box_max: 1.74943,0.25
obs transformed box_min: 0.0956431,-0.517409
obs transformed box_max: 1.08784,0.474788
[INFO] [1712780669.767033042] [lane_blocker_node]: Obstacle rmf_obstacle_detector_laserscan_0 is still in the vicinity of lane tinyRobot_43
[INFO] [1712780669.767117245] [lane_blocker_node]: There are 0 lanes with changes to the number of obstacles in their vicinity
[INFO] [1712780670.764610955] [lane_blocker_node]: Obstacle rmf_obstacle_detector_laserscan_0 was previously in the vicinity of 2 lanes
================================================

```

Thank you and apologies for so many questions!

https://github.com/open-rmf/rmf_obstacle/assets/80419042/d48e6ab6-7f8e-4dea-9156-28c33269a112

[[obstacle_not_showing_in_rviz.zip](https://github.com/open-rmf/rmf_obstacle/files/14973195/obstacle_not_showing_in_rviz.zip)](https://github.com/open-rmf/rmf_obstacle/files/14973195/obstacle_not_showing_in_rviz.zip)

# Steps to reproduce the bug

1. Launch rmf demo office with `. install/setup.bash ros2 launch rmf_demos_gz office.launch.xml`
2. Run the bridge for gz and ros topics `ros2 run ros_gz_bridge parameter_bridge --ros-args -p config_file:=src/boston-office-simulation/ros_gz_bridge_config/ign.yaml`
3. run the laserscan detector node `. install/setup.bash ros2 run rmf_obstacle_detector_laserscan laserscan_detector`
4. configure and activate the laserscan detector node `ros2 lifecycle set /laserscan_obstacle_detector configure ros2 lifecycle set /laserscan_obstacle_detector activate`
5. Run the transform publisher for the lidar `python3 src/boston-office-simulation/tf_python/tf_pub.py`
6. Run the lane blocker node `. install/setup.bash ros2 run rmf_obstacle_ros2 lane_blocker_node`

# Expected behavior

As obstacle is placed in Gazebo, it will show up in Rviz, and robot lanes blocked by this obstacle will be closed

# Actual behavior

Obstacle doesn't show up in Rviz and robot lanes are not closed
